version: '2'
services:
  postgresql:
    image: postgres:12.3
    container_name: icommerce-postgresql
    # volumes:
    #     - ~/volumes/jhipster/gateway/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gateway
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
